app:
  name: myapp
  image: krishnamoorthy1/awseks-nginx
  tag: "462"
  port: 80
  replicas: 2

service:
  type: NodePort
  port: 80
  nodeport: 30080

httpRoute:
  enabled: false

ingress:
  enabled: false
